### PR TITLE
added a logout modal 

### PR DESCRIPTION
**Pull request by 17arindam**
-added a logout modal when user clicks on logout button it ask if they want to continue logout

https://github.com/user-attachments/assets/a8e5641a-c711-415a-91b5-eaaea0ae72b3

## Summary by CodeRabbit

- **New Features**
	- Introduced a logout confirmation modal in the Navbar for enhanced user experience.
	- Added a new contributor, Jay Shah, to the README.

- **Bug Fixes**
	- Removed the entry for the previous contributor, Bashua Mutiat, from the README.

- **Style**
	- Improved formatting and readability of the Navbar component's JSX structure.

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
can you change the modal color acc to UI color
@17arindam

**Comment by 17arindam** [comment]
image
@RamakrushnaBiswal is this better?

**Comment by RamakrushnaBiswal** [comment]
@17arindam yepp

**Comment by RamakrushnaBiswal** [comment]
@17arindam reolve the conflicts please i will merge the PR

**Comment by 17arindam** [comment]
@RamakrushnaBiswal i have resolved merge conflicts

**Pull request merged**
