### PR TITLE
Added Newsletter-Form

### PR DESCRIPTION
**Pull request by meghanakn473**
I have added newsletter form in the footer section at the place u have asked me for,
This form helps users to subscribe and be updated with events.

Screenshot (186)

@RamakrushnaBiswal please review and allow merge and assign the level 3, gssoc-extd, hacktoberfest labels
i hope ull conside it

## Summary by CodeRabbit

- **New Features**
	- Introduced a newsletter subscription feature with a new `NewsletterForm` component for user email input.
	- Added a new API route for handling newsletter subscriptions.
	- Removed the Help and Support page from the application.

- **Bug Fixes**
	- Corrected a typo in the error handling middleware import.

These updates enhance user interaction with the newsletter service, improve application stability, and streamline the user experience by removing outdated features.

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
@meghanakn473 its not match with the UI and make alignment properly

**Comment by RamakrushnaBiswal** [comment]
@meghanakn473 also resolve coderabit suggestions

**Comment by meghanakn473** [comment]
> @meghanakn473 its not match with the UI and make alignment properly

What kind of modifications do u want ? Can u please describe @RamakrushnaBiswal

**Comment by RamakrushnaBiswal** [comment]
@meghanakn473 remove the background 
image
make something like this and add it here
image

**Comment by meghanakn473** [comment]
@RamakrushnaBiswal please check now

**Comment by RamakrushnaBiswal** [comment]
@meghanakn473 make it responsive 
Screenshot_2024-10-22-12-29-13-49_40deb401b9ffe8e1df2f1cc5ba480b12

**Review by RamakrushnaBiswal — APPROVED** [review]

**Comment by meghanakn473** [comment]
@RamakrushnaBiswal please allow merge and assign labels

**Comment by RamakrushnaBiswal** [comment]
@meghanakn473 did you make it responsive
image

**Comment by RamakrushnaBiswal** [comment]
@meghanakn473 
image
not yet

**Comment by meghanakn473** [comment]
> @meghanakn473 image not yet

hey 
@RamakrushnaBiswal sorry for the delay in response, i had my exams couldnt check with it...

**Comment by meghanakn473** [comment]
@RamakrushnaBiswal can u please guide me how can i make it responsive according to wt ur asking please??

**Comment by meghanakn473** [comment]
@RamakrushnaBiswal 
Screenshot (193)
please check now and allow merge

**Comment by meghanakn473** [comment]
@RamakrushnaBiswal please check and allow merge

**Comment by meghanakn473** [comment]
@RamakrushnaBiswal please update??

**Pull request merged**
