### PR TITLE
changes the font of navbar, added a hover effect

### PR DESCRIPTION
**Pull request by Ayush215mb**
I have changes the font of the navbar options and added a hover effect, upon hovering the text changes to a light shade of orange, text is magnified a little and gets shifted toward above in y direction. 
If you need any changes, feel free to tell me.

https://github.com/user-attachments/assets/4beb61c1-95ae-4c45-8bb7-0115a13ea0ff

## Summary by CodeRabbit

- **New Features**
	- Enhanced navigation menus with improved hover effects for both desktop and mobile views.
	- Introduced new fonts ("Playfair Display" and "Poppins") for enhanced typography.
	- Added styles for scrollbar customization, including hover effects.

- **Style**
	- Reformatted class names and indentation in the Navbar for improved readability.
	- Updated contributor information in the README for clarity and accuracy.

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
image

extra spaces are remove that change the fonts yo poppins

**Comment by RamakrushnaBiswal** [comment]
also resolve the conflicts

**Comment by Ayush215mb** [comment]
Remove the empty space from the right side of the navbar??
Just confirm this thing and the rest of the changes are done, then I will commit the new changes and resolve the conflicts.

**Comment by RamakrushnaBiswal** [comment]
Well make a PR @Ayush215mb

**Comment by Ayush215mb** [comment]
I have created the PR, there are no conflicts now, vercel only needs your authorization to run the checks.(that's not a conflict)

**Comment by RamakrushnaBiswal** [comment]
@Ayush215mb still 🥲

**Comment by Ayush215mb** [comment]
@RamakrushnaBiswal There were no conflicts when i last saw it, they were created because you added some PR so the content of  file changes from your repo creating a conflict.
Nonetheless I have resolved them so please accept it asap and REMEMBER to assign the LABELS.

**Comment by Ayush215mb** [comment]
this is becoming a lot confusing, I am creating a new PR

**Comment by RamakrushnaBiswal** [comment]
@Ayush215mb see vercel deployment failed 
What I can do 
Screenshot_2024-10-06-14-10-25-09_40deb401b9ffe8e1df2f1cc5ba480b12

**Pull request closed without merging**
