### PR TITLE
Add Multilingual Translator

### PR DESCRIPTION
**Pull request by 17arindam**
This PR integrates the google multilingual translator enabling users to translate content into multiple languages. This feature enhances accessibility and user experience for a diverse audience.

https://github.com/user-attachments/assets/4438efb3-31bc-4274-8760-898ec285644f

## Summary by CodeRabbit

- **New Features**
	- Introduced a Google Translate component for enhanced language support.
	- Integrated the Google Translate functionality into the footer section of the app.

- **Documentation**
	- Updated the contributors section in the README.md to include new contributors and adjusted formatting for consistency.

### CODE REVIEW

**Comment by 17arindam** [comment]
@RamakrushnaBiswal please review my pr issue no - #176

**Comment by 17arindam** [comment]
@RamakrushnaBiswal i have resolved conflicts please review my pr

**Comment by RamakrushnaBiswal** [comment]
hi @17arindam it doesn't looks good and also don't use css use tailwind css.
Make it little bit small

**Comment by 17arindam** [comment]
@RamakrushnaBiswal actually the classes are coming from google translator api because of that the tailwind code is not implementing correctly i have improved the ui of google translator
image

**Comment by 17arindam** [comment]
@RamakrushnaBiswal please review my changes

**Comment by 17arindam** [comment]
@RamakrushnaBiswal please check the updated ui

**Comment by RamakrushnaBiswal** [comment]
LGTM 🚀

**Pull request merged**
