### PR TITLE
Home Text Typer, Footer Compo, Not Found Page and other UI Updation  

### PR DESCRIPTION
**Pull request by AliGates915**
1. **Before**
**Screenshot (697)** 
**After**
Screenshot (696)

2.**Before**
Screenshot (691)
**After**
Screenshot (694)

3.**Before**
Screenshot (698)
**After**
Screenshot (700)

4.**Before**
Screenshot (701)
**After**
Screenshot (695)

@RamakrushnaBiswal check my PR. 

## Release Notes

- **New Features**
	- Added social media icons for Facebook, Instagram, and TikTok in the footer.

- **Improvements**
	- Enhanced visual layout of the "404 Not Found" page.
	- Adjusted heading size on the Landing page for better readability.
	- Refined navigation button positioning in the Review Carousel for improved accessibility.

- **Cosmetic Changes**
	- Renamed menu item from "Boardgames" to "BoardGames" in the Navbar.

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
1 and 4 not needed just remove that

**Comment by AliGates915** [comment]
@RamakrushnaBiswal Check my other PR.

**Comment by RamakrushnaBiswal** [comment]
@AliGates915 why did you closed it

**Comment by AliGates915** [comment]
> @AliGates915 why did you closed it

Because bro already open to another PR. Plz bro merge it.

**Pull request closed without merging**
