### PR TITLE
added new navbar design

### PR DESCRIPTION
**Pull request by sanayamahajan-23**
Before design:
image

Screenshot of my designs 
image

image

Here is the design I added as navbar. It has gradient effect along with glassmorphism effect. I also added the new hover effect as you can see from the screenshots and also the active page has button-gradient effect.I hope you like my design. also add the level label so I can keep track of my points.

## Summary by CodeRabbit

- **New Features**
	- Introduced a visually enhanced navigation bar with a glassmorphism effect.
	- Added mobile menu styles for improved aesthetics and functionality.
	- Implemented dynamic rendering of navigation links for a more streamlined experience.

- **Bug Fixes**
	- Simplified state management in the Navbar component by removing unnecessary complexity.

- **Style**
	- Updated CSS styles for navigation links, including hover effects and active link indicators.

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
hi @sanayamahajan-23 first of all i didn't assigned you the issue and i didn't use any vanila css for designing (i used tailwind )
color combination is not good.

**Comment by sanayamahajan-23** [comment]
but you assigned me this issue

**Comment by RamakrushnaBiswal** [comment]
@sanayamahajan-23 i really sorry about it but

**Comment by sanayamahajan-23** [comment]
Okay so it is assigned to me right ? If it is then could you please provide me with some time until tomorrow

**Comment by RamakrushnaBiswal** [comment]
@sanayamahajan-23 sure

**Pull request closed without merging**
