### PR TITLE
Chore: fixed past date selection for reservation

### PR DESCRIPTION
**Pull request by lade6501**
Fixes: #237 

**Changes In PR**
- Setting minimum date as today's date 
- Added validation for manual input 

**Demo**
Playcafe-Disabled-Previous_Date

https://github.com/user-attachments/assets/551a58df-a446-46bf-af7a-8b0332442681

## Summary by CodeRabbit

- **New Features**
	- Enhanced date selection in the registration component to prevent users from selecting dates before today.
	- Implemented dynamic minimum date setting based on the current date.

- **Bug Fixes**
	- Added validation to alert users when an invalid date is selected.

- **Style**
	- Updated formatting in the signup component for consistency, including import statements and password strength meter display logic.

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
@lade6501 good work but instead using normal alert user antd message for that 
ref:- check in login page

**Comment by lade6501** [comment]
> @lade6501 good work but instead using normal alert user antd message for that ref:- check in login page

Yeah was thinking the same , but was not sure thanks for feedback.

**Comment by lade6501** [comment]
Hi @RamakrushnaBiswal  like this ?
Screenshot 2024-10-15 at 8 18 20 AM

**Comment by RamakrushnaBiswal** [comment]
@lade6501 yes

**Comment by RamakrushnaBiswal** [comment]
@lade6501 commit ?

**Comment by lade6501** [comment]
> @lade6501 commit ?

just pushing

**Comment by lade6501** [comment]
pushed @RamakrushnaBiswal, sorry for delay.

**Comment by RamakrushnaBiswal** [comment]
one conflict

**Review by RamakrushnaBiswal — APPROVED** [review]

**Pull request merged**
