### PR TITLE
 BUG: fix the main page footer non res. #406 

### PR DESCRIPTION
**Pull request by AE-Hertz**
BUG: fix the main page footer non res. #406 

Closes: #406 

Fixes : 
1. Fixed the footer , and drastically imporved code of footer by removing redundancy.
2. fixed the light mode color subscribe newsletter was not visible.
3. Fixed it for mobile screens.
4. Even fixed the misalignments of Social, Contact Us section.

Screenshot:
Screenshot 2024-10-28 123743

## Summary by CodeRabbit

- **New Features**
	- Redesigned footer layout for improved responsiveness, featuring a two-column design on larger screens.
	- Enhanced styling for the newsletter form and navigation components for better visual appeal.

- **Bug Fixes**
	- Improved visual spacing and hierarchy within the footer for better readability across devices.

### CODE REVIEW

**Comment by AE-Hertz** [comment]
if you are upgrade the level, as i spent alot of time to imporve code, that would be good. rest your decision. 

Happy to contribute.

**Comment by RamakrushnaBiswal** [comment]
@make the component little bit smaller

**Comment by AE-Hertz** [comment]
@RamakrushnaBiswal can you please specify you want the newsletter component to be a little more smaller for mobile devices right?

**Comment by AE-Hertz** [comment]
@RamakrushnaBiswal i made changes and make newsletter section a bit more smaller. hoping to get my PR merged. thank you.

**Review by RamakrushnaBiswal — APPROVED** [review]

**Comment by RamakrushnaBiswal** [comment]
@AE-Hertz good work

**Comment by AE-Hertz** [comment]
@RamakrushnaBiswal thank you.

**Pull request merged**
