### PR TITLE
Global messages implemented

### PR DESCRIPTION
**Pull request by 17arindam**
-A success message is displayed when a user logs in or logs out successfully.
-An error message is shown if there is a failure during login/logout attempts.
Screenshot 2024-10-05 012300

## Summary by CodeRabbit

- **New Features**
	- Introduced user authentication feedback in the Navbar, displaying success messages upon login/logout.
	- Added Ant Design as a new dependency for enhanced UI components.
	- Implemented lazy loading for images in the Boardgame and ReviewCarousel components to improve performance.
	- Added a health check endpoint to monitor server status.

- **Bug Fixes**
	- Improved error handling during login and logout processes to provide clearer user feedback.
	- Enhanced feedback form submission with error handling and loading states.

- **Chores**
	- Updated the `.gitignore` to include additional environment configuration files.

### CODE REVIEW

**Comment by 17arindam** [comment]
@RamakrushnaBiswal please review my pr issue no- #76

**Comment by RamakrushnaBiswal** [comment]
@17arindam resolve the conflicts

**Comment by 17arindam** [comment]
@RamakrushnaBiswal i have resolved the merge conflict

**Comment by RamakrushnaBiswal** [comment]
@17arindam you made too much changes with many files 
Please don't mind create a new PR

**Pull request closed without merging**
