### PR TITLE
Added Perspective Hover Effect for Popular Board Games Card and Code cleanup : Issue no #106

### PR DESCRIPTION
**Pull request by AbhijitMotekar99**
## I added hover effects, and I also cleaned up the register.jsx and boardgame.jsx code for the cards using the map method to make it shorter.

https://github.com/user-attachments/assets/a4b955af-4c29-4050-b48c-29a3f701560c

https://github.com/user-attachments/assets/b830f16d-0216-4cae-bf40-78ba6a88fff8

## Release Notes

- **New Features**
  - Enhanced visual effects with new hover interactions on board game cards and dynamic rendering of game data.
  - Introduction of new CSS styles for improved aesthetics, including glow effects, text outlines, and custom scrollbar styles.

- **Bug Fixes**
  - Streamlined rendering logic in the Register and Boardgame components for better performance.

- **Documentation**
  - Updated styles and component structures to improve maintainability and user experience.

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
@AbhijitMotekar99 1st video hover effect doesn't look good

**Comment by AbhijitMotekar99** [comment]
Hey @RamakrushnaBiswal 
I will change it.

**Comment by AbhijitMotekar99** [comment]
Hey @RamakrushnaBiswal 
I changed hover effect and also enhanced overall card UI.

**Comment by RamakrushnaBiswal** [comment]
@AbhijitMotekar99 lgtm :)

**Pull request merged**
