### PR TITLE
Dark Mode

### PR DESCRIPTION
**Pull request by jainaryan04**
@RamakrushnaBiswal fixed conflicts and updated navbar
image

## Release Notes

- **New Features**
	- Introduced dark mode support across various components, enhancing user experience in low-light environments.
	- Added `ThemeToggle` and `Preloader` components for improved navigation and loading indications.
	- Implemented a new `useDarkMode` hook for managing theme states.

- **Styling Enhancements**
	- Updated background and text colors for multiple components to ensure visual clarity in both light and dark modes.
	- Enhanced visual presentation of components like `Membership`, `About`, `Boardgame`, and others to improve aesthetics in dark mode.

- **Bug Fixes**
	- Adjusted styles for better visibility and consistency across themes in components like `Membership`, `About`, `Boardgame`, and others.

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
@jainaryan04 there are some conflicts 
and dont use normal css use tailwind css @jainaryan04

**Comment by jainaryan04** [comment]
converted to tailwind @RamakrushnaBiswal 
I have fixed the conflicts now but if you merge any pr before mine there will be conflicts again. please fix them if they arise now because otherwise, we will be going in circles.

**Comment by RamakrushnaBiswal** [comment]
@jainaryan04 
image
here the cards are not visible 
image

**Comment by jainaryan04** [comment]
fixed @RamakrushnaBiswal

**Comment by RamakrushnaBiswal** [comment]
@jainaryan04 
image
image

cahnge it

**Comment by jainaryan04** [comment]
@RamakrushnaBiswal fixed

**Comment by RamakrushnaBiswal** [comment]
@jainaryan04 resolve the conflicts

**Comment by jainaryan04** [comment]
It won't help
@RamakrushnaBiswal 
I resolved them twice before. If you merge any pr till i resolve them, there will be conflicts again
Can you please resolve them ?

**Pull request closed without merging**
