### PR TITLE
#234 resolved issue regarding the footer alignment

### PR DESCRIPTION
**Pull request by rithvikreddybasani**
Before this there is some extra space coming below the footer like this 

image

But now i resolved this issue

image

@RamakrushnaBiswal 

## Summary by CodeRabbit

- **New Features**
	- Enhanced clarity and responsiveness of the footer component.
  
- **Bug Fixes**
	- Improved footer height management for better layout consistency.
  
- **Documentation**
	- Updated README with new contributor information and clarified installation instructions.
	- Added comments to clarify the purpose of various elements and styles within the footer.

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
@rithvikreddybasani see in mobile view it happes and don't change the overlap style 
image

**Comment by rithvikreddybasani** [comment]
Should i modify it in mobile version too @RamakrushnaBiswal?

**Comment by RamakrushnaBiswal** [comment]
@rithvikreddybasani yhnjust for mobile vr

**Comment by rithvikreddybasani** [comment]
image

 Changed In Mobile Version,

@RamakrushnaBiswal

**Comment by RamakrushnaBiswal** [comment]
image

@rithvikreddybasani

**Pull request closed without merging**
