### PR TITLE
Feat/contactus page

### PR DESCRIPTION
**Pull request by PriyanshuValiya**
Some Minor Changes as per coderabit suggestions.

## Release Notes

- **New Features**
  - Introduced a contact form for user inquiries, accessible via the new "Contact Us" menu item.
  - Added client-side validation and error handling for the contact form submissions.
  
- **Improvements**
  - Enhanced navigation with the addition of the "Contact Us" entry in the navbar.
  - Implemented rate limiting for form submissions to prevent spam.

- **Bug Fixes**
  - Improved error handling for module loading across various routes.

- **Documentation**
  - Updated routing structure to include the new contact form component.

### CODE REVIEW

**Review by RamakrushnaBiswal — COMMENTED** [review]
@PriyanshuValiya addd some screenshots or video

**Comment by PriyanshuValiya** [comment]
Screenshot 2024-10-28 094430

**Review by RamakrushnaBiswal — APPROVED** [review]

**Comment by RamakrushnaBiswal** [comment]
@PriyanshuValiya resolve the conflicts

**Comment by PriyanshuValiya** [comment]
@RamakrushnaBiswal If I follow all coderabit suggestions, final email functionality is not working properly..

**Comment by RamakrushnaBiswal** [comment]
@PriyanshuValiya As per your issue . you didn't add a contact us page you just add the feedback section again in different route
create a contact us page instead

**Pull request closed without merging**
