### PR TITLE
Added password strength meter

### LINKED ISSUE #220: Feat: Adding a responsive password strength meter
### Describe the feature

The password meter enhances use experience.
Adding a meter which can also change color and displays password strength below the password field elevates user experience.

### Add ScreenShots

Screenshot 2024-10-09 070324

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by PavanTeja2005**
I have added a responsive password strength meter which enhances user experience.

Fix #220 

image

## Summary by CodeRabbit

- **New Features**
	- Enhanced password strength analysis in the Signup component, offering users real-time feedback with a visual progress bar and descriptive text.
- **Bug Fixes**
	- Removed outdated environment variable declarations that were no longer needed.
- **Chores**
	- Updated package dependencies to include the `zxcvbn` library for improved password security.

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
@PavanTeja2005 resolve the conflicts

**Comment by PavanTeja2005** [comment]
@RamakrushnaBiswal Please check, I have resolved conflicts.

**Comment by RamakrushnaBiswal** [comment]
@PavanTeja2005 
image

**Comment by PavanTeja2005** [comment]
Please install the react  library

**Comment by PavanTeja2005** [comment]
"zxcvbn"

**Comment by PavanTeja2005** [comment]
It might be in npm modules already just check npm install or please install it using "npm install zxcvbn"

**Comment by RamakrushnaBiswal** [comment]
@PavanTeja2005 in vercel it automatically installed i think you are not push package.json file

**Comment by PavanTeja2005** [comment]
@RamakrushnaBiswal please try and let me know. I will change the code if it doesn't work

**Comment by RamakrushnaBiswal** [comment]
push your `package.json` file

**Comment by PavanTeja2005** [comment]
Ok . I will check again. I will do it

**Comment by PavanTeja2005** [comment]
@RamakrushnaBiswal please can you merge , i won't get points otherwise..

**Comment by RamakrushnaBiswal** [comment]
@PavanTeja2005 the progress bar is not working 
image

**Comment by PavanTeja2005** [comment]
Please retry with this new file

**Comment by PavanTeja2005** [comment]
It was working for me.
image
image

**Comment by PavanTeja2005** [comment]
@RamakrushnaBiswal Please check this. It was working at me

**Comment by RamakrushnaBiswal** [comment]
@PavanTeja2005 now its working

**Review by RamakrushnaBiswal — APPROVED** [review]
LGTM

**Pull request merged**
