### PR TITLE
 Enhance Coffee Cup Image with Parallax Effect

### LINKED ISSUE #52: Feat: Add Parallax Mouse hover effect in home page
### Describe the feature

I want to add parallax mouse hover effect in the below coffee image in home page, just like it is there in the menu page. It will improve user experience of your website. I'll finish it within an hour. Kindly assign it to me under hacktober fest and GSSoC extd label.

### Add ScreenShots

image_2024-10-03_153816720

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by anshi05**
Fixes #52 

It  introduces enhancements to the Landing component by applying a parallax effect to the coffee cup image. The key changes include:

- Parallax Effect: The image moves slightly based on the mouse position, creating an engaging user experience. The translation effect is calculated to ensure smooth motion, enhancing the interactive feel of the landing page.

**Changes Made:**
Updated the parallaxEffect to combine both translation and rotation in the transform property of the motion.img element.
Ensured that the rotation does not interfere with the parallax effect, maintaining the visual consistency of the design.

**Testing:**

- [x] Verified the responsiveness and visual effect across different screen sizes and browsers.
- [x] Ensured no negative impact on existing functionalities or layouts.

## Summary by CodeRabbit

- **New Features**
	- Enhanced the landing page with interactive mouse tracking and animations.
	- Introduced a parallax effect for the coffee cup image that responds to mouse movements.
	- Added AOS animations for improved visual engagement.

- **Bug Fixes**
	- Minor structural adjustments to improve the layout and remove unnecessary code.

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
@anshi05 can you some 3d type effect on it
or 1st the coffee cup will come whilw scrolling the texts will come

**Comment by anshi05** [comment]
Ok let me try if I can do that . Though I've never done that before.

**Comment by RamakrushnaBiswal** [comment]
@anshi05 sure

**Comment by anshi05** [comment]
I have added the fading animation to the text "PLAYCAFE". So now the coffee mug is visibele and then the text comes on top of it  after few seconds enhancing overall UI.

**Pull request closed without merging**
