### PR TITLE
chatbot has been added.

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
#340 solved. @RamakrushnaBiswal can you please review this .
the chatbot is working.

https://github.com/user-attachments/assets/ddb051f3-e54c-42db-b44f-fc2cd876f5fa

Screenshot 2024-10-19 at 11 52 51 AM

## Summary by CodeRabbit

- **New Features**
	- Introduced a chatbot integration with a dedicated React component.
	- Added a configuration for the chatbot, enabling it to function within the application.
	- Enhanced the Back to Top button with improved visibility control based on scroll position.

- **Bug Fixes**
	- Implemented cleanup for the chatbot script to ensure proper resource management.
	- Improved rendering behavior of the Back to Top button for better user experience.

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@RamakrushnaBiswal can you please reiview this.

**Comment by T-Rahul-prabhu-38** [comment]
@RamakrushnaBiswal can you please reiview this, i have one more to make.

**Comment by RamakrushnaBiswal** [comment]
@T-Rahul-prabhu-38 actually today I am traveling 🥲 
So I will review the PR in evening

**Comment by T-Rahul-prabhu-38** [comment]
sure i was just getting back to all the repo's PR i made because sometimes they will be inactive. 
sorry if i disturbed.

**Comment by RamakrushnaBiswal** [comment]
@T-Rahul-prabhu-38 
image

make horizontal alligned

**Comment by T-Rahul-prabhu-38** [comment]
i had fixed it let me check.

**Review by RamakrushnaBiswal — APPROVED** [review]

**Comment by T-Rahul-prabhu-38** [comment]
yes it is fixed.
Screenshot 2024-10-20 at 9 04 54 PM

**Review by RamakrushnaBiswal — APPROVED** [review]
Good work

**Pull request merged**
