### PR TITLE
Feat/Image Upload Cloudinary

### LINKED ISSUE #319: Feat: Set Up Cloudinary for Universal Image Upload Functionality
### Describe the feature

Description: We need to integrate Cloudinary for handling image uploads across the cafe website, ensuring a scalable and reusable solution that can be used for various features. This API will allow for future functionality, such as adding images to event creation, user profile editing, and other media-related needs. The implementation should be universal and not restricted to any single part of the website.

Tasks:
Install and Configure Cloudinary:
Install the Cloudinary SDK in both the backend and frontend if necessary.
Create a Cloudinary account and configure API keys in a .env file to keep them secure.
Set up Cloudinary configurations (e.g., API secret, API key, cloud name) on the server.

Develop a Universal Image Upload API:
Implement a reusable API endpoint to handle image uploads. This API should:
Accept file uploads (e.g., images from forms).
Integrate with Cloudinary for storing and managing images.
Return the uploaded image's URL for storage in the database.

Ensure that this API can be used for multiple features, including:
Event creation (upload event banners or images).
User profile page (upload profile pictures).
Future features that require image management.

Client-Side Integration:
Create a frontend utility function that can call the image upload API whenever needed.
Add file input handling for event creation and profile editing forms to allow users to upload images.
Display a preview of the image after it is selected for upload (optional).

Database Integration:
Ensure the URLs of uploaded images are stored correctly in the database for their respective features.
Adjust the existing database schema if necessary to accommodate these image links (e.g., events and user profiles).

Validation and Error Handling:
Add proper validation for image uploads:
Restrict file types to valid image formats (e.g., JPEG, PNG).
Set file size limits.
Handle errors gracefully on both frontend and backend, providing feedback to users (e.g., if an image fails to upload or is too large).
Secure the upload endpoint by verifying that only authenticated users can upload images (relevant for profile editing).

Testing and Deployment:
Test the API thoroughly for different scenarios (successful upload, invalid file types, large file sizes).
Ensure images are correctly uploaded to Cloudinary and the correct URLs are returned.

Additional Considerations:
Plan for handling multiple image uploads in the future if needed (e.g., for galleries).
Ensure security and privacy around images uploaded by users (especially profile pictures).
Keep API endpoints extensible for future media-related features.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes #319 Adding functionality of upload image in cloudinary and store its secure_url in database of User.profilePicture.

Code changes: 
Index.js => simply call to cloudinaryConnect and also use middleware to parse files using package of express-fileupload.

callIndex

CloudinaryConnect require CLOUD_NAME, CLOUD_API_KEY, CLOUD_SECRET you can get all of these by registering in cloudinary

cloudcall

Image uploader function having many parameter you can also edit the quality of image and also sent video as well.

imageuploader

Admin image upload=> it fetches file from req.body if file exist then it will upload to cloudinary otherwise skip and after uploading it will give you secure_url by which you can see your upload image.

adminImage

Customer image upload=> it fetches file from req.body if file exist then it will upload to cloudinary otherwise skip and after uploading it will give you secure_url by which you can see your upload image.

customerImage

@RamakrushnaBiswal Please review and merge it with labels:)

## Release Notes

- **New Features**
	- Added a file input for image uploads in the Signup component, enhancing user experience during registration.
	- Contributors section in the README updated to include new contributors, improving project visibility.
	- Cloudinary integration for image uploads added to backend functionality.
	- Enhanced backend functionality to handle image uploads for both admin and customer creation.

- **Bug Fixes**
	- Corrected a typo in the error middleware import.

- **Chores**
	- New environment variables added to backend configuration.
	- Updated package dependencies to include Cloudinary and express-fileupload.

### CODE REVIEW

**Comment by harshbhar0629** [comment]
@RamakrushnaBiswal I also add image filed during signup if any one want image upload during signup then it can upload and stored in database.

**Comment by RamakrushnaBiswal** [comment]
@harshbhar0629 resolve code rabit suggestions

**Comment by harshbhar0629** [comment]
@RamakrushnaBiswal this code is also work and given changes are not very small so that i can change easily

**Comment by RamakrushnaBiswal** [comment]
Resolve conflicts @harshbhar0629

**Comment by harshbhar0629** [comment]
> Resolve conflicts @harshbhar0629

Ok

**Comment by harshbhar0629** [comment]
@RamakrushnaBiswal All conflicts are resolved:)

**Pull request merged**
