### PR TITLE
Refactor routing and improve layout with Navbar and Footer

### LINKED ISSUE #13: Performance Optimization and Modularization Improvements
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

I identified several optimization and modularization issues that are causing the site to perform slowly.

Proposed Changes:

Refactor code for better modularization.
Optimize performance to enhance loading speeds and overall user experience.
This may involve changing multiple files across the project.
Next Steps: I would like to request to be assigned to this issue to implement the necessary changes.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue
- [X] I check the issue doesn't exist

### PR DESCRIPTION
**Pull request by tejasbenibagde**
### Summary
This PR addresses issue #13 by refactoring the routing in the application to enhance navigation and improve layout management.

### Changes Made
- Created a separate folder for the router to better organize routing logic.
- Updated `<a>` tags in the Navbar to `<Link>` components from React Router, ensuring that page navigation does not cause full page reloads.
- Integrated `<Outlet />` in the main application layout, allowing a consistent display of the Navbar and Footer across all pages without reloading them.

### Benefits
- Improved user experience with seamless navigation.
- Cleaner code structure with centralized routing logic.
- Enhanced maintainability and scalability for future features.

### Related Issue
- Closes #13

## Summary by CodeRabbit

- **New Features**
	- Introduced a new layout-based routing structure for improved navigation.
	- Added a dedicated routing configuration to streamline application views.

- **Bug Fixes**
	- Removed unnecessary components (Navbar and Footer) from various pages for a cleaner layout.

- **Documentation**
	- Updated routing and navigation logic for better user experience.

- **Refactor**
	- Simplified the `App` component structure by focusing on shared components.
	- Enhanced the `Navbar` component with improved routing links.

### CODE REVIEW

**Comment by tejasbenibagde** [comment]
@RamakrushnaBiswal  please take a look at this

**Comment by RamakrushnaBiswal** [comment]
@tejasbenibagde events and reservation routes are not working 
image

**Comment by tejasbenibagde** [comment]
wait for a minute I'll take a look into it.

**Comment by tejasbenibagde** [comment]
@RamakrushnaBiswal I've fixed the router please take a look at it.

**Pull request merged**
