### PR TITLE
Created Feedback Submission System 

### PR DESCRIPTION
**Pull request by samar12-rad**
This PR integrates the frontend feedback form with the backend, introduces a feedback controller, and sets up routes for future handling of feedback submissions, for the issue #33 . 

Changes Made:

Feedback Form Backend Integration:
Connected the existing frontend feedback form to the backend system, enabling users to submit their feedback.

Database Model for Feedback:
Created a database model to store feedback, capturing fields such as user comments, email, and user name.

Feedback Routes:
Added backend routes, including a POST route (/submit-feedback) to handle feedback submissions and store them in the database.
Additional routes were created for future management and retrieval of feedback data.

Feedback Controller:
Implemented a feedback controller to manage logic for handling feedback submissions and future feedback-related functionality.

Response Handling:
Users receive success or failure responses based on whether their feedback was submitted successfully.

## Release Notes

- **New Features**
	- Introduced a feedback submission feature, allowing users to provide feedback through a dedicated form.
	- Added a welcome message and API versioning to the feedback endpoint.

- **Improvements**
	- Enhanced the feedback form to handle submissions asynchronously with improved error handling and user feedback during submission.
	- Updated the application to ignore environment configuration files in version control.

- **Bug Fixes**
	- Resolved issues related to feedback submission by validating input data.

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
resolve @coderabit suggestions

**Comment by samar12-rad** [comment]
@GitGuardian scan

**Comment by samar12-rad** [comment]
@RamakrushnaBiswal , performed code rabbit changes, removed risks created by git guardian

**Comment by samar12-rad** [comment]
As the code rabbit is suggesting to use a library for logging errors, such as Logger, but there is no such library pressent neither in forntend or backend, can i create an issue to imcorporate the error of whole backend with logger?

**Comment by RamakrushnaBiswal** [comment]
ok then @samar12-rad  go for it

**Comment by samar12-rad** [comment]
@RamakrushnaBiswal . i create the issue. Also, is this PR completed?

**Comment by RamakrushnaBiswal** [comment]
resolve the conflicts please @samar12-rad

**Comment by samar12-rad** [comment]
Added pre save hook with validator.js library.
image

**Comment by samar12-rad** [comment]
One conflict remaining for which i have already raised #72 . @RamakrushnaBiswal 
image

**Comment by RamakrushnaBiswal** [comment]
@samar12-rad LGTM 🚀

**Pull request merged**
