### PR TITLE
 Enhancement: login page #446 

### PR DESCRIPTION
**Pull request by AE-Hertz**
Enhancement: login page #446 

Closes: #446 

Things which have been improved-
- fixed toggle password eye button for login and signup page
- fix image overflow in login page
- fix image overflow in signup page
- drastically reduced img file size by 60%
 

Before:
Screenshot 2024-11-02 134830
Screenshot 2024-11-02 130803
Screenshot 2024-11-02 134844

After:

Screenshot 2024-11-02 131327
Screenshot 2024-11-02 134358
Screenshot 2024-11-02 131341

## Release Notes

- **New Features**
	- Introduced "Remember Me" functionality in the login process.
	- Added a button for signing up with Google on the signup page.

- **Improvements**
	- Updated layout and styling for the Login, Signup, and Email Verification pages, including dark mode support.
	- Enhanced user input validation and error handling for OTP verification.
	- Updated image assets across multiple components for a more optimized visual experience.

- **Documentation**
	- Updated contributors' section in the README file.

### CODE REVIEW

**Comment by AE-Hertz** [comment]
if you can upgrade the level that would be appreciated. thank you/

**Comment by RamakrushnaBiswal** [comment]
@AE-Hertz resolve the conflicts

**Comment by AE-Hertz** [comment]
> @AE-Hertz resolve the conflicts

merge conflicts resolved.

**Comment by AE-Hertz** [comment]
if you can upgrade the level that would be appreciated . thank you

**Pull request merged**
