### PR TITLE
feat: Dark Mode

### LINKED ISSUE #322: Feat: Dark Mode
### Describe the feature

I want to add a toggle button that would allow the users to switch to dark mode.

### Add ScreenShots

image
image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by jainaryan04**
closes #322 
fixed merge conflicts
@RamakrushnaBiswal 
image

## Release Notes

- **New Features**
  - Introduced dark mode support across various components, enhancing user experience in low-light environments.
  - Added a theme toggle feature for users to switch between light and dark themes easily.

- **Styling Enhancements**
  - Updated styling for several components, including the Navbar, Footer, and various pages, to support dark mode with appropriate color contrasts.
  - Improved visual presentation of elements like buttons, headers, and backgrounds to ensure consistency across themes.

- **Documentation**
  - Updated the README to reflect new contributors and their details.

### CODE REVIEW

**Comment by jainaryan04** [comment]
@RamakrushnaBiswal please merge

**Comment by RamakrushnaBiswal** [comment]
@jainaryan04 resolve the conflicts 
i will merge PRs according FCFS to its happening

**Comment by jainaryan04** [comment]
done @RamakrushnaBiswal

**Comment by RamakrushnaBiswal** [comment]
@jainaryan04 
image
signup page not working

**Comment by jainaryan04** [comment]
@RamakrushnaBiswal

**Pull request merged**
