### PR TITLE
Update Register.jsx

### PR DESCRIPTION
**Pull request by neeru24**
fixes: #280 

## Summary by CodeRabbit

- **New Features**
	- The registration form has been renamed to `ReservationForm` with a new layout.
	- Simplified state management for form submission.

- **Improvements**
	- Enhanced form validation and data logging.
	- Cleaned up JSX structure for better maintainability and visual consistency.

- **Documentation**
	- Updated contributors' section in the README to reflect current contributors accurately.

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
@neeru24 attact some screen recording or screenshots

**Comment by neeru24** [comment]
> @RamakrushnaBiswal Can you check on Preview? Or should I add?

**Comment by RamakrushnaBiswal** [comment]
@neeru24  i didn't see any changes so kindly add

**Comment by RamakrushnaBiswal** [comment]
@neeru24 you didn't change anything 
as per your issue you need to add hover effect but i did't see anything what you add,
so i asked for video or screenshot but you didn't provide thats why i didn't merge it

**Comment by neeru24** [comment]
> @neeru24 you didn't change anything 
> as per your issue you need to add hover effect but i did't see anything what you add,
> so i asked for video or screenshot but you didn't provide thats why i didn't merge it 

Sure, I'll add some screenshots.. Give me some time. By tomorrow, I'll do so
Thank you

**Comment by neeru24** [comment]
Here, in this video, you'll not get the whole same UI or styling. For the modification purposes, I just replicated the main UI of form and added the effects.

Kindly merge it. 

https://github.com/user-attachments/assets/503736a4-08d8-4c67-aaf3-1ccddbe259f4

**Comment by RamakrushnaBiswal** [comment]
@neeru24 you removed many code which is not required for adding a just hover effect
i am not going to merge it

**Pull request closed without merging**
