### PR TITLE
Improvement: Making the Home page Images and text Responsive and visually appealing

### PR DESCRIPTION
**Pull request by Suhas-Koheda**
1. The text size on the front page is changed as per the device type larger font for desktop and smaller ones for mobile 
2. The svg color of the hamburger menu is changed to black to appeal visually 

## Summary by CodeRabbit

- **New Features**
	- Enhanced layout and styling for the Landing component.
	- Introduced a new height utility for improved responsiveness.

- **Bug Fixes**
	- Resolved navigation issues in the ReviewCarousel to ensure seamless review transitions.

- **Style**
	- Improved responsiveness and visual hierarchy across various screen sizes.
	- Updated text sizes for better readability and contrast.

# Screenshot
## Mobile
image
image
image
image
image
image

## Desktop 
image
image
image
Rest remains the same

### CODE REVIEW

**Comment by Suhas-Koheda** [comment]
@RamakrushnaBiswal please look into it

**Comment by RamakrushnaBiswal** [comment]
@Suhas-Koheda attach some screenshots

**Comment by Suhas-Koheda** [comment]
@RamakrushnaBiswal I have updated the pr 
pleas have a look 
https://play-cafe-lake.vercel.app/
this is the deployment of the changes you can have  a look here too

**Comment by RamakrushnaBiswal** [comment]
In mobile view make the landing page text alignment left and make the height is screen

**Comment by Suhas-Koheda** [comment]
In mobile a centered approach would be good maybe?

**Comment by RamakrushnaBiswal** [comment]
Ok I will review and merge at night 
Till then you can rise another issues

**Comment by Suhas-Koheda** [comment]
I have completed changing the height of screen 
The text thing - centered approach would be good i feel 
Before a merge you can have a look at my deployment to have an idea of how it would look

**Comment by RamakrushnaBiswal** [comment]
It looks good btw

**Comment by RamakrushnaBiswal** [comment]
hi @Suhas-Koheda can you make another PR 
image

to change the font size for all the devices

**Comment by Suhas-Koheda** [comment]
Change to? 
I have used variable fonts everywhere 
Like 9xl on desktop and 7xl and further

**Pull request merged**
