### PR TITLE
Kindeauth integrated using react

### PR DESCRIPTION
**Pull request by 17arindam**
-Installed @kinde-oss/kinde-auth-react library for KindeAuth.
-Updated Navbar component to reflect the authentication state (login, register, logout).
-Created .env file to handle environment variables securely.
-Updated App.js to wrap the application in the KindeProvider for authentication context.

## Summary by CodeRabbit

- **New Features**
	- Added Kinde authentication support, enhancing user login and registration processes.
	- Updated Navbar to conditionally display authentication options based on user status.

- **Documentation**
	- Introduced new environment variables in the example configuration file for Kinde integration.

- **Chores**
	- Updated `.gitignore` to exclude sensitive environment files from version control.
	- Added dependency `@kinde-oss/kinde-auth-react` to the project.

### CODE REVIEW

**Comment by 17arindam** [comment]
@RamakrushnaBiswal please review

**Comment by RamakrushnaBiswal** [comment]
@17arindam resolve coderabit suggestions

**Comment by 17arindam** [comment]
@RamakrushnaBiswal please review my pr

**Comment by RamakrushnaBiswal** [comment]
add only login

**Comment by 17arindam** [comment]
@RamakrushnaBiswal so should i create register somewhere else because otherwise it is showing
image

**Pull request merged**
