### PR TITLE
fixed bug in selected language

### PR DESCRIPTION
**Pull request by Pushpa472**
@RamakrushnaBiswal #374 I fixed bug in selected language, also added marathi language.
before
image
after
image

I also improved footer section
before
image
after
image

## Summary by CodeRabbit

- **New Features**
	- Introduced the `Google` component in both the `Home` and `Navbar` components.

- **Bug Fixes**
	- Enhanced responsiveness of the footer text and layout, ensuring better user experience across different screen sizes.

- **Style**
	- Adjusted styling for the footer and Google Translate dropdown for improved visual consistency and usability.

### CODE REVIEW

**Comment by Pushpa472** [comment]
@RamakrushnaBiswal if there is any issue in  code plz let me known

**Review by RamakrushnaBiswal — APPROVED** [review]
LGTM

**Comment by Pushpa472** [comment]
@RamakrushnaBiswal above suggested label should be level 2 please check it , assign proper label

**Comment by RamakrushnaBiswal** [comment]
@Pushpa472 its a bot , Hope you understand

**Comment by Pushpa472** [comment]
ok

**Pull request merged**
