### PR TITLE
Create proper Backend Folder Structure with MVC and added routing with API folder

### PR DESCRIPTION
**Pull request by samar12-rad**
This is for the Issue #35  @RamakrushnaBiswal.
Added Dependencies - cors, mongoose, zod and dotenv
Added Routes folder - has index file to configure routes.
added root API call, which transfers to routes/index.js.
added reservation Controller - Which will handle all requests for resservation.
added Mongoose 
created Models folder which creates mongoose schema on mongoose models for database handling. 

## Release Notes

- **New Features**
	- Introduced a reservation creation functionality, allowing users to make reservations with specified guests, date, and time.
	- Added a welcome message for the restaurant API.

- **Enhancements**
	- Implemented CORS support and JSON request parsing for improved API accessibility.
	- Established a MongoDB connection for data persistence.
	- Added a new API endpoint for managing reservations.

- **Development Improvements**
	- Added a dedicated router for reservation management, streamlining API interactions.
	- Introduced a new environment variable for MongoDB connection.

### CODE REVIEW

**Comment by samar12-rad** [comment]
@RamakrushnaBiswal , i removed mongo from .env in latest commit, is it still error
image

**Comment by samar12-rad** [comment]
Resolving them

**Comment by samar12-rad** [comment]
@RamakrushnaBiswal, is it fine now?

**Comment by samar12-rad** [comment]
gitrabbit check now

**Comment by samar12-rad** [comment]
@RamakrushnaBiswal , it is saying to use new library and folder for handling errors, Can I create new issue for that?

**Comment by RamakrushnaBiswal** [comment]
@samar12-rad you branch is not update with main branch so it shows deployment failed please update the branch 

after mergering your 1st PR then work upon it , otherwise conflicts you know

**Comment by samar12-rad** [comment]
Thank you for suggestion @RamakrushnaBiswal. Sorry I forgot updating last time, I will update my branch with latest merges and push, is that all?

**Comment by RamakrushnaBiswal** [comment]
yes @samar12-rad

**Comment by samar12-rad** [comment]
image
I resolved all changes, on pushing it is saying nothing to commit, working tree clean, not pushing because everything up to date.

**Comment by samar12-rad** [comment]
@RamakrushnaBiswal pls check

**Comment by samar12-rad** [comment]
@RamakrushnaBiswal, I added env.example .

**Comment by samar12-rad** [comment]
@RamakrushnaBiswal Can you assign labels to this pr?

**Comment by samar12-rad** [comment]
@RamakrushnaBiswal , can you please assign labels to this pr?

**Comment by RamakrushnaBiswal** [comment]
@samar12-rad done :)

**Comment by samar12-rad** [comment]
THank you :)

**Pull request merged**
