### PR TITLE
Adding Custom Modal in Menu Page 

### PR DESCRIPTION
**Pull request by dev129**
### Description:

This PR addresses issue #196 by introducing a custom modal to the menu page, aimed at capturing customer attention and enhancing their experience on the website. By utilizing **framer-motion**, the modal provides a visually appealing and interactive invitation for users to engage with our offerings.

#### Key Features:

- **Dynamic Modal Design**: The modal showcases an attractive graphic and an enticing message, encouraging users to dive deeper into the menu.
- **Highlighted Call-to-Action**: The “Take Me There” button is prominently styled to stand out, enticing users to take action and discover more.
- **Smooth Interaction**:
  - **Close Button**: Allows users to dismiss the modal without navigating away.
  - **Take Me Button**: Closes the modal and directs users seamlessly to the /menu page.

### Changes Included:

- Added the custom modal component with animated opening and closing behavior using framer-motion.
- Integrated a responsive design for optimal viewing across devices.
- Styled buttons for visibility, including hover effects for better interaction feedback.
- Implemented accessibility features to ensure a user-friendly experience for all visitors.
- A built in timer of 5 mins for quickly availing the offer.

### Impact:

This feature is designed to draw users' attention to the menu page, encouraging them to explore our offerings and potentially increasing user engagement and conversions.

Please review the changes and provide any feedback or suggestions for improvement!

## Summary by CodeRabbit

- **Documentation**
	- Updated the contributors' list in the README to reflect current contributors.
	- Removed several previous contributor entries and added new contributors.
	- Updated GitHub links for some contributors to ensure accuracy.
  
- **New Features**
	- Introduced a new modal component, `IncentiveOffers`, displaying exclusive offers with a countdown timer.
	- Added functionality to manage modal visibility in the Menu component.

- **Bug Fixes**
	- Commented out the password strength checking functionality in the Signup component, affecting password input handling. 

- **Chores**
	- Added a new dependency for a lightweight slider and carousel component in the project.

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
@dev129 you didn't do anything in this PR just update readme.md which is not required

**Comment by dev129** [comment]
No wait I actually did it , lemme just check once again

**Comment by RamakrushnaBiswal** [comment]
@dev129  you make 361 files for a single issue i can't aprove it

**Comment by dev129** [comment]
Wait what ?

**Pull request closed without merging**
