### PR TITLE
Fixed the About and review carousel section

### PR DESCRIPTION
**Pull request by sajalbatra**
Fixed the things
image
image
image

## Summary by CodeRabbit

- **New Features**
	- Enhanced layout and styling of the About component for improved visual presentation.
	- Introduced a "Read more" functionality in the ReviewCarousel for displaying full reviews or truncated versions based on user interaction.
	- Dynamic adjustment of displayed reviews in the ReviewCarousel based on window width.

- **Bug Fixes**
	- Improved readability of review text by consolidating multiline strings.

- **Style**
	- Adjusted CSS classes and layout properties for better consistency and responsiveness across components.
	- Updated class names for the About component to enhance text contrast and responsiveness.

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
hi @sajalbatra 
image
don't change this in large and md screen size (keep as it is) in mobile view its good
other's are good

**Comment by sajalbatra** [comment]
> hi @sajalbatra image don't change this in large and md screen size (keep as it is) in mobile view its good other's are good

Hey,
Please check again i have fixed the top margin

**Comment by RamakrushnaBiswal** [comment]
image
i mean don't change it in large and md screen just make change in small screen

**Comment by RamakrushnaBiswal** [comment]
@sajalbatra 
image
make it responsive

**Pull request merged**
