### PR TITLE
global message implemented

### PR DESCRIPTION
**Pull request by 17arindam**
Screenshot 2024-10-05 012300
-implemented global message for success and error of login routes
-show respective message after user comes back from kinde auth screen

## Summary by CodeRabbit

- **New Features**
	- Enhanced authentication handling in the Navbar component.
	- Success messages displayed for login and logout actions.
- **Bug Fixes**
	- Improved error handling for login and logout processes.
- **Chores**
	- Added Ant Design library for improved UI components.

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
Hi @17arindam I will merge it

**Comment by 17arindam** [comment]
@RamakrushnaBiswal wait let me fix the coderabbit issue first

**Comment by RamakrushnaBiswal** [comment]
@17arindam yh
Btw I forgot that the form and all are implemented

**Comment by 17arindam** [comment]
@RamakrushnaBiswal okay can i work on any backend issue ?

**Comment by 17arindam** [comment]
@RamakrushnaBiswal can you please merge it now

**Pull request merged**
