### PR TITLE
Added the Dockerfile

### LINKED ISSUE #155: Feat: Add Dockerfile
### Describe the feature

I want to add Dockerfile to the root of the project. 
A Dockerfile creates a containerized environment for applications, ensuring consistent deployment across different environments, simplifying scaling and isolation, and eliminating conflicts between dependencies and system configurations.

### Add ScreenShots

file example

Screenshot 2024-10-08 160011

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by haseebzaki-07**
fixes #155 

command to build the image : docker build -t playcafe .
command to run the docker image : docker run -p 5173:5173 -p 3000:3000 playcafe

Screenshot 2024-10-08 171621

## Summary by CodeRabbit

- **New Features**
	- Introduced a multi-stage build process for improved deployment of the Node.js application, supporting both frontend and backend components.
	- Enabled concurrent running of frontend and backend development servers for a streamlined development experience.
	- Added `.dockerignore` files for both frontend and backend to optimize the Docker build context by excluding unnecessary files.
	- Implemented a new `start.sh` script to initiate both frontend and backend environments seamlessly.
	- Configured a `docker-compose.yml` file to support a multi-service development environment with hot-reloading capabilities.
	- Enhanced the README.md with a Docker setup section, providing instructions for building and running the application using Docker.

- **Chores**
	- Updated Dockerfile to optimize the build process and ensure efficient use of resources.

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
@haseebzaki-07 solve code rabbit sugesstions

**Comment by haseebzaki-07** [comment]
hey @RamakrushnaBiswal I have added code rabbit suggestions

**Comment by RamakrushnaBiswal** [comment]
@haseebzaki-07 ok how can i use it i mean as a contributor

**Comment by RamakrushnaBiswal** [comment]
Can you make a single command to do all the things

**Comment by haseebzaki-07** [comment]
@RamakrushnaBiswal In that case we need to have docker-compose.yaml file that will run the application with a single command.

**Comment by RamakrushnaBiswal** [comment]
Ok do that I will merge it ;)

**Comment by RamakrushnaBiswal** [comment]
@haseebzaki-07 did you added `docker-compose.yaml` file

**Comment by haseebzaki-07** [comment]
well I was a bit busy @RamakrushnaBiswal It'll be ready by night.

**Comment by haseebzaki-07** [comment]
hey @RamakrushnaBiswal I have added the docker compose file.

command to run  docker-compose.yml :  docker-compose up --build

**Comment by RamakrushnaBiswal** [comment]
@haseebzaki-07 add the commands in the reademe.md file in the repo
and how contributor can use it

**Comment by haseebzaki-07** [comment]
@RamakrushnaBiswal I have updated the Readme.md

**Review by RamakrushnaBiswal — APPROVED** [review]

**Pull request merged**
