### PR TITLE
Add git contributors page

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #341
Screenshot 2024-10-25 at 5 40 01 PM
hey @RamakrushnaBiswal please review my PR

## Summary by CodeRabbit

- **New Features**
	- Introduced a new "CONTRIBUTORS" menu item in the navigation bar.
	- Added a `Contributors` component that fetches and displays a list of contributors from a specified GitHub repository.
	- New route added for the `Contributors` component, accessible via `/contributors`.

- **Bug Fixes**
	- Enhanced error handling and loading states in the `Contributors` component.

### CODE REVIEW

**Comment by shubhagarwal1** [comment]
fix: #341

> Screenshot 2024-10-25 at 5 40 01 PM hey @RamakrushnaBiswal please review my PR

**Comment by RamakrushnaBiswal** [comment]
@shubhagarwal1 add the _**contributors**_  button in footer and resolve coderabbit changes

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 add the _**contributors**_ button in footer and resolve coderabbit changes

Hey @RamakrushnaBiswal, i will add the bhtton the footer but as you can see as many changes i do the coderabbit will still suggest the changes please dont got that way .

**Comment by RamakrushnaBiswal** [comment]
@shubhagarwal1 resolve the conflicts

**Pull request closed without merging**
