### PR TITLE
feat/Improved Button Styles for Better Readability in both light & dark mode

### LINKED ISSUE #417: Feat: Improve Button Readability in Dark Theme for Events Slot Booking Section
### Describe the feature

**Description:**  
In the Events section, specifically within the Slot Booking area, the button appearance currently displays effectively in light theme. However, in dark theme, the button does not adapt its colors, which creates readability issues due to low contrast between the button text and background. Improving the button’s color adaptation for dark theme will enhance accessibility and maintain a consistent user experience across themes.

**Steps to Reproduce:**  
1. Navigate to the Events section using navbar.
2. Switch to dark theme.
3. Observe the Slot Booking button and note the readability issues due to color contrast.

**Expected Behavior:**  
The button should dynamically adjust to dark theme, using colors that ensure readability and visual consistency with other dark theme elements.

**Proposed Solution:**  
Implement color adaptations for the Slot Booking button in dark theme to increase text-background contrast. This may involve:
- Modifying button background and text colors specifically for dark theme.
- Ensuring accessibility standards by achieving sufficient contrast ratio.

**Screenshots:**  
image
image

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have starred the repository
- [X] I'm a gssoc-24-extd contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by CoderFleet**
### Description
Fixes #417 
This PR addresses the readability of the **"Book your Slot"** button in the event page, specifically within the **"Events"** section. Using Tailwind CSS classes, I refined the button's styling to ensure optimal contrast and visual coherence in both light and dark modes. The revised styling aligns with the UI theme, enhancing user experience across themes.

### Changes Made
- Updated the **"Book a Seat"** button styling with Tailwind classes to improve readability in both light and dark modes.
- Ensured the button blends seamlessly with the UI, maintaining visual consistency.

### Updates
- Updated Button Theming and styles for both light and dark mode states...

### Screenshots 
Light Mode:
image
---
Dark Mode:
image

## Summary by CodeRabbit

- **New Features**
	- Enhanced styling for the "Book your slot" button in the event list for improved visual clarity and responsiveness.
	- Updated background and hover colors to better align with theme variations.
	- Set text color to white for better readability against the new background.

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
@CoderFleet red colot is not match with the UI

**Comment by CoderFleet** [comment]
@RamakrushnaBiswal sorry, for that... Is there any specific color choice do you have in mind
I will try to adjust that for both dark and light mode

**Comment by RamakrushnaBiswal** [comment]
just swap the text color @CoderFleet 
like white bg with black text color and vice versa

**Comment by CoderFleet** [comment]
@RamakrushnaBiswal Sorry for the late commit...I have made the changes and updated the PR

**Review by RamakrushnaBiswal — APPROVED** [review]

**Pull request merged**
